class Test {
    void foo () throws Exception {
    }

    void bar () throws Exception {
        foo();
    }
}
